---
language: "php"

php:
  - 7.1

before_script:
- composer install
- wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.6.0/php-cs-fixer.phar -O php-cs-fixer
- chmod +x ./php-cs-fixer

script:
- ./php-cs-fixer fix --dry-run --diff
