---
language: "php"

php:
  - 7.1

before_script:
- composer install
- wget $(wget -O - https://api.github.com/repos/FriendsOfPHP/PHP-CS-Fixer/releases | grep browser_download_url | grep 'php-cs-fixer.phar' | head -n 1 | cut -d '"' -f 4) -O php-cs-fixer
- chmod +x ./php-cs-fixer

script:
- ./php-cs-fixer fix --dry-run --diff
